/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117987-g6e49b86996-20241202"
#endif /* AVUTIL_FFVERSION_H */
